
service: hicetnunc-apiv2

frameworkVersion: '2.37.0'

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x

functions:
  handler:
    handler: index.handler
    timeout: 120
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
      - http: 
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'

custom:
  serverless-offline:
    httpPort: 3001